import Link from 'next/link';
import { Search, BookOpen, GraduationCap, ArrowRight } from 'lucide-react';
import { createClient } from '@/lib/supabase/server';

const branches=[['CSE','Computer Science & Engineering'],['EE','Electrical Engineering'],['IT','Information Technology'],['ECE','Electronics & Communication'],['AEIE','Applied Electronics & Instrumentation'],['CE','Civil Engineering']];
export default async function Home(){const supabase=await createClient();const [{count:resourceCount},{data:recent}]=await Promise.all([supabase.from('papers').select('*',{count:'exact',head:true}).eq('status','approved'),supabase.from('papers').select('id,title,year,exam_type').eq('status','approved').order('created_at',{ascending:false}).limit(6)]);return <>
<section className="hero"><div className="container py-20 md:py-28"><div className="max-w-3xl"><span className="rounded-full bg-white/15 px-4 py-2 text-sm">University Institute of Technology · The University of Burdwan</span><h1 className="mt-7 text-4xl font-extrabold tracking-tight md:text-6xl">Your academic resources, organized for UIT.</h1><p className="mt-5 text-lg text-blue-50 md:text-xl">Find question papers, notes, lab reports, assignments and study materials by branch, semester and subject.</p><form action="/resources" className="mt-8 flex max-w-2xl overflow-hidden rounded-xl bg-white p-1 shadow-2xl"><input name="q" className="min-w-0 flex-1 px-4 py-3 text-slate-900 outline-none" placeholder="Search resources, subjects or codes..."/><button className="rounded-lg bg-[#0b1f3a] px-5 py-3 font-semibold text-white"><Search className="inline" size={18}/> Search</button></form></div></div></section>
<section className="container py-14"><div className="grid gap-4 sm:grid-cols-3"><div className="card p-6"><BookOpen className="text-[#0b5ed7]"/><p className="mt-4 text-3xl font-bold">{resourceCount ?? 0}</p><p className="text-slate-500">Approved resources</p></div><div className="card p-6"><GraduationCap className="text-[#0b5ed7]"/><p className="mt-4 text-3xl font-bold">6</p><p className="text-slate-500">Engineering branches</p></div><div className="card p-6"><p className="text-3xl font-bold">8</p><p className="mt-4 text-slate-500">Semesters organized</p></div></div></section>
<section className="bg-white py-14"><div className="container"><div className="flex items-end justify-between"><div><p className="font-semibold text-[#0b5ed7]">EXPLORE</p><h2 className="mt-1 text-3xl font-bold">Choose your branch</h2></div><Link href="/branches" className="hidden text-sm font-semibold md:block">View all <ArrowRight className="inline" size={16}/></Link></div><div className="mt-8 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{branches.map(([code,name])=><Link key={code} href={`/branch/${code.toLowerCase()}`} className="card p-6 transition hover:-translate-y-1"><span className="text-sm font-bold text-[#0b5ed7]">{code}</span><h3 className="mt-2 text-lg font-semibold">{name}</h3><p className="mt-2 text-sm text-slate-500">Browse semester-wise resources</p></Link>)}</div></div></section>
<section className="container py-14"><h2 className="text-3xl font-bold">Recent uploads</h2><div className="mt-7 grid gap-4 md:grid-cols-2 lg:grid-cols-3">{(recent??[]).map((p:any)=><Link href={`/resource/${p.id}`} key={p.id} className="card p-5"><p className="font-semibold">{p.title}</p><p className="mt-2 text-sm text-slate-500">{p.exam_type} · {p.year ?? 'Year not specified'}</p></Link>)}</div></div>
</>}
